
export default new Map([
["src/content/projects/01-hoping-forest-development/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F01-hoping-forest-development%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/02-library-ar-tales/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F02-library-ar-tales%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/03-face-tracking-hoka/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F03-face-tracking-hoka%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/04-localization-tool/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F04-localization-tool%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/05-save-game-tool/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F05-save-game-tool%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/06-murder-by-the-book/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F06-murder-by-the-book%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/07-cursed-tetrominoes/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F07-cursed-tetrominoes%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/08-y-el-pan/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F08-y-el-pan%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/09-echo/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F09-echo%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/10-buscando-a-bigotes/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F10-buscando-a-bigotes%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/11-carrera-nautilus/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F11-carrera-nautilus%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/12-depth-of-mind/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F12-depth-of-mind%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/13-precious-time/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F13-precious-time%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/20-experimental-animation/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F20-experimental-animation%2Findex.mdx&astroContentModuleFlag=true")],
["src/content/projects/21-documentaries-collage-projects/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fprojects%2F21-documentaries-collage-projects%2Findex.mdx&astroContentModuleFlag=true")]]);
		