
import __ASTRO_IMAGE_IMPORT_Z15vrf7 from "./bannerImage.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F01-hoping-forest-development%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZNPnr6 from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F01-hoping-forest-development%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_5wIV7 from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F02-library-ar-tales%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z22y2dP from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F03-face-tracking-hoka%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1CUAFo from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F04-localization-tool%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_13VWUr from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F05-save-game-tool%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1myyuM from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F06-murder-by-the-book%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1QMPsP from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F07-cursed-tetrominoes%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1SBoY1 from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F08-y-el-pan%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_107B8j from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F09-echo%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1q89Y6 from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F10-buscando-a-bigotes%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZOsQaC from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F11-carrera-nautilus%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_tQRMt from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F12-depth-of-mind%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z6tbOE from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F13-precious-time%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1ArchO from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F20-experimental-animation%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZXgFN from "./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F21-documentaries-collage-projects%2Findex.mdx";
export default new Map([["./bannerImage.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F01-hoping-forest-development%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z15vrf7], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F01-hoping-forest-development%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZNPnr6], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F02-library-ar-tales%2Findex.mdx", __ASTRO_IMAGE_IMPORT_5wIV7], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F03-face-tracking-hoka%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z22y2dP], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F04-localization-tool%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1CUAFo], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F05-save-game-tool%2Findex.mdx", __ASTRO_IMAGE_IMPORT_13VWUr], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F06-murder-by-the-book%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1myyuM], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F07-cursed-tetrominoes%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1QMPsP], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F08-y-el-pan%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1SBoY1], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F09-echo%2Findex.mdx", __ASTRO_IMAGE_IMPORT_107B8j], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F10-buscando-a-bigotes%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1q89Y6], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F11-carrera-nautilus%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZOsQaC], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F12-depth-of-mind%2Findex.mdx", __ASTRO_IMAGE_IMPORT_tQRMt], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F13-precious-time%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z6tbOE], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F20-experimental-animation%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1ArchO], ["./featuredImage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2F21-documentaries-collage-projects%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZXgFN]]);
		